const GET_ADMIN_BY_ID= "GET_ADMIN_BY_ID"
const ADD_ADMIN= "ADD_ADMIN"
const UPDATE_ADMIN= "UPDATE_ADMIN"
const DELETE_ADMIN= "DELETE_ADMIN"

export { GET_ADMIN_BY_ID, ADD_ADMIN, UPDATE_ADMIN, DELETE_ADMIN}